# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: 'oas'
        # Keep oas at v20.x for compatibility with api@6.1.3
        versions: ['21.x', '22.x', '23.x', '24.x', '25.x', '26.x', '27.x', '28.x', '29.x', '30.x']
      - dependency-name: 'next'
        # Stay on Next.js v15 for now
        versions: ['>=16.0.0']
      - dependency-name: '@next/mdx'
        # Stay on Next.js v15 for now
        versions: ['>=16.0.0']
      - dependency-name: '@next/third-parties'
        # Stay on Next.js v15 for now
        versions: ['>=16.0.0']
      - dependency-name: '@next/eslint-plugin-next'
        # Stay on Next.js v15 for now
        versions: ['>=16.0.0']
      - dependency-name: 'eslint-config-next'
        # Stay on Next.js v15 for now
        versions: ['>=16.0.0']
    groups:
      npm-dependencies:
        # Group all npm dependencies together
        patterns:
          - '*'
