name: Mark and close stale Pull Requests

on:
  schedule:
    - cron: '30 0 * * *' # Runs daily at 00:30 UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-pr-stale: 30 # Mark PRs as stale after 30 days of inactivity
          days-before-pr-close: 7 # Close stale PRs 7 days after being marked stale
          stale-pr-message: 'This Pull Request has been inactive for 30 days and will be closed in 7 days if no further activity occurs. Please update or close this PR if it is no longer relevant.'
          close-pr-message: 'This Pull Request has been closed due to inactivity.'
          stale-pr-label: 'stale'
          exempt-draft-pr: false
